Docker postgres pg_cron fix
Haidra-Org/AI-Horde pull request #447
Opened 2024-09-03 12:26 UTC by dex3r

postgres image used in docker-compose now has the required `pg_cron` extension.

2024-09-03 12:27 UTC, dex3r commented
Closes #448

2024-09-03 12:32 UTC, tazlin commented
Thanks for taking the initiative. 

However, can you adjust this to use the [version controlled package](https://github.com/Haidra-Org/haidra-docker-images/pkgs/container/ai-horde-postgres) as we do in the [workflows](https://github.com/Haidra-Org/AI-Horde/blob/3f2bcff9486060962dada20d6300f92c39ad1e4f/.github/workflows/maintests.yml#L51) so we do not have multiple copies of the [custom postgres Dockerfile](https://github.com/Haidra-Org/haidra-docker-images/tree/main/ai-horde/postgres)?

2024-09-03 12:32 UTC, tazlin requested changes
Please use the existing https://github.com/Haidra-Org/haidra-docker-images instead as noted above.

2024-09-27 13:29 UTC, closed without merging

2024-09-27 13:29 UTC, tazlin commented
Superseded by #455.